### PR TITLE
Updated gradle & android project to use variables from root project

### PR DESCRIPTION
**Pull request by XenorPLxx**
@rayronvictor and @taranda updated project so it works with newest React Native version. It would be great, if we could get that merged.

### CODE REVIEW

**Comment by XenorPLxx** [comment]
I've updated PR to use better pattern used in react-native-camera https://github.com/react-native-community/react-native-camera/blob/master/android/build.gradle and in react-native-fabric corymsmith/react-native-fabric#177

**Comment by taranda** [comment]
I have not tested, but I have seen this pattern work successfully in other packages.

**Comment by erickreutz** [comment]
Will this be backward compatible with older versions of react native?

**Comment by XenorPLxx** [comment]
I have not tested it against older versions. Not all of them will be compatible - that's for sure. But it goes for most packages with native code, e.g. react-native-svg has whole table which version should be use with which react-native.

**Comment by andreyslyusar** [comment]
@erickreutz This can be backward compatible by specifying `ext` version in build.gradle
```
ext {
    compileSdkVersion   = 26
    buildToolsVersion   = "26.0.2"
    targetSdkVersion    = 26
}
```

**Comment by alexmngn** [comment]
What is the status on this? It will unblock people using more recent version of Gradle and RN .56

**Comment by taranda** [comment]
@alexmngn, good question. See #269.

**Comment by jaycee425** [comment]
Is there a plan for this to be merged?

**Comment by XenorPLxx** [comment]
I've also added `Changed Android repository order` due to https://stackoverflow.com/questions/50563407/could-not-find-play-services-basement-aar/51213879#51213879

**Pull request closed without merging**
