### PR TITLE
make react-native-windows peer dependency optional

### LINKED ISSUE #581: `react-native-windows` as a peer dep might not be needed?
I just tried to use npm 7 to install this package in a mobile RN project with react 16. npm complained that rnw needs react 17 and I have 16 so they are not compatible.

I don't think rnw should be a peer dep, should it? It doesn't provide anything for mobile, and if a project is doing RN on win, then it does have that dep already.

Does that make sense?

### PR DESCRIPTION
**Pull request by mjgallag**
fixes #581

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

### CODE REVIEW

**Review by luancurti — APPROVED** [review]
Thank You! Awesome! 🎉

**Comment by jkey5stones** [comment]
@luancurti would it be possible to get a patch release containing this fix?

**Comment by jspizziri** [comment]
@luancurti would love to see a patch release with this, as otherwise we're effectively forced to downgrade to npm 6 to use this package.

**Comment by arcollector** [comment]
please could you update the npm version to reflect this change?

**Comment by luancurti** [comment]
Sry for the delay!

**Comment by Mcculloughj** [comment]
{
  "os": [
    "!win32"
  ]
}

**Pull request merged**
