### PR TITLE
Shorter integration for ios + cocoapods issues are fixed

### PR DESCRIPTION
**Pull request by maxkomarychev**
* ruby scripts were refactored
* environment values are now exposed to Info.plist via xcconfig file
* environment values became available in Build Settings
* cocoapods integration fixed - no need to add custom code to Podfile!
(as suggested in this PR: https://github.com/luggit/react-native-config/pull/329)

Demo project is available here: https://github.com/maxkomarychev/rncfg2-demo
There are two branches: "pods" and "nopods" demonstrating how it can work with and without pods

run `react-native run-ios` and then `ENVFILE=.env.staging react-native run-ios` and this will create two different apps with different bundle ids and names

### CODE REVIEW

**Comment by redcancode** [comment]
i would love to have this library support being installed as a pod so i can remove my workaround to generate the dotenv headers. i hope this pull request solves that problem 👍🙂

**Comment by galkahana** [comment]
thank you!

**Comment by ido-sa** [comment]
great!

**Comment by digitaldavenyc** [comment]
@maxkomarychev I pulled your repo and tested against my project and it's still failing

**Comment by maxkomarychev** [comment]
@digitaldavenyc would you mind provide more details?

**Comment by maxkomarychev** [comment]
@redcancode hey, have you managed to try my pr?

**Comment by redcancode** [comment]
@maxkomarychev i was hoping it will get merged without problems :) i will write a comment when i've tried it

**Comment by patrickkempff** [comment]
@erickreutz @jordanbrown is this library still maintained? If not is it possible to transfer the owner ship to somebody that can take care of this library and all responsibilities that come with it? that would help A LOT 👍

**Comment by atasanchez** [comment]
Hi, you know when this PR would merged? I have a big problem with this issue!

**Comment by grit96** [comment]
Do we still need to run a clean when switching the `envfile`?
The build appears to be caching the `xcconfig` after even though the contents of `tmp.xcconfig` are changing.

**Comment by grit96** [comment]
According to [this](https://stackoverflow.com/questions/3730186/how-do-i-force-xcode-to-rebuild-the-info-plist-file-in-my-project-every-time-i-b), Xcode caches the `info.plist` and should be removed as part of the build `pre-actions`.

**Comment by leethree** [comment]
when is this going to be released?

**Comment by rborn** [comment]
@maxkomarychev just wanted to thank you 😍

**Pull request merged**
