### PR TITLE
[info.plist] Add support for using constants in the Info.plist

### PR DESCRIPTION
**Pull request by mlanter**
Add the ability to use config in the `Info.plist` file.  

Based on https://coderwall.com/p/euesdq/use-defined-values-in-info-plist

### CODE REVIEW

**Comment by mlanter** [comment]
cc: @GantMan @pedro

**Comment by pedro** [comment]
wow, looks great! you rock @mlanter :+1:

**Comment by pedro** [comment]
Just a small note here – I noticed some characters doesn't seem to work, like "/".

This is puzzling me... tried changing the `GeneratedInfoPlistDotEnv` to define constants as strings, just like the example you linked above:

```
#define __RN_CONFIG_FOO @"a/b"
```

But when I read that var from my plist it seems like the whole thing is turned into a string:

```
NSString *foo = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"Test"];
NSLog(@"foo=%@", foo); // prints: foo=@"a/b"
```

**Comment by mlanter** [comment]
@pedro I had originally tried that article verbatim, but I too saw the issue where it includes the `@""`.  The preprocessor is basically doing a find / replace so it makes sense.  Although it does have some logic for special characters which isn't what we want, but I'm not certain of the best way to handle those.

One idea is to "we can pass the -traditional flag to the Info.plist Other Preprocessor Flags build setting in Xcode."  Does that help with the slashes?

from https://developer.apple.com/library/content/technotes/tn2175/_index.html

**Comment by pedro** [comment]
It works! I'll update the readme.

**Pull request merged**
