### PR TITLE
Adding mavenCentral() as jcenter() is shutting

### PR DESCRIPTION
**Pull request by maheshwarimrinal**
Adding mavenCentral() as jcenter() is shutting down

### CODE REVIEW

**Review by r3nya — APPROVED** [review]

**Comment by matteodanelli** [comment]
Any ETA about this merge?

**Comment by pedpess** [comment]
JCenter is shutting down tomorrow 1st of February. If merge doesn't happen before that there's a workaround using `patch-package` here https://github.com/luggit/react-native-config/issues/635#issuecomment-1011456089

**Review by BogdanRad — APPROVED** [review]

**Review by luancurti — APPROVED** [review]

**Comment by luancurti** [comment]
@maheshwarimrinal Thank you!

**Review by luancurti — APPROVED** [review]
@maheshwarimrinal Thank you!

**Pull request merged**
