### PR TITLE
fixes: class name collision with native react-native-config

### LINKED ISSUE #667: ReactNativeConfig.h name collision w/ React Native 0.68 iOS
React Native 0.68 iOS introduces `<react/config/ReactNativeConfig.h>` in `AppDelegate.mm`  as part of optional new-architecture support, conflicting with **react-native-config**'s `ReactNativeConfig.h`.

It seems the docs should be updated to make it clear these are different classes and provide an example of how to work around the name collision.

Thanks!

### PR DESCRIPTION
**Pull request by philpettican118**
Fixes #667

### CODE REVIEW

**Comment by HolySamosa** [comment]
@philpettican118   Thanks so much for working on this!   Practically, I'm sure this is a safe renaming, but as a heads up [Apple reserves 2-letter prefixes for it's own frameworks](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html):

> In order to keep class names unique, the convention is to use prefixes on all classes. You’ll have noticed that Cocoa and Cocoa Touch class names typically start either with NS or UI. Two-letter prefixes like these are reserved by Apple for use in framework classes.
> 
> . . .  
> 
> Your own classes should use three letter prefixes. These might relate to a combination of your company name and your app name, or even a specific component within your app. 
>

**Comment by philpettican118** [comment]
Hey @HolySamosa , It's using three letter prefixes i.e **RNC** e.g. **RNC**Config

**Comment by HolySamosa** [comment]
[facepalm] Duh, sorry @philpettican118 .  I just realized I was only looking at one of the earlier commits.  This is what I get for skipping coffee this morning...

**Comment by luancurti** [comment]
@philpettican118 Thanks for spend your time to fix the problem. I'll take a look as soon as possible.

**Pull request merged**
