### PR TITLE
update ios headers for react native 0.40

### PR DESCRIPTION
**Pull request by beeglebug**
See #71 and https://github.com/facebook/react-native/releases/tag/v0.40.0

### CODE REVIEW

**Comment by kevinnguy** [comment]
Will this be merged anytime soon?

**Comment by parshap** [comment]
Can this change get published to npm?

**Comment by GantMan** [comment]
Yup, will do soon.   I need to review and test (which takes a bit of time).  If you don't see this published in the next 24hrs bug me to get on it!

**Comment by GantMan** [comment]
Woops, looks like i don't have npmjs access. I can't publish this to node modules.

**Comment by parshap** [comment]
@pedro: Can you publish this?

**Comment by pedro** [comment]
Oh yes! Published 0.2.2.

Lets get you access @GantMan, what's your npm user?

**Comment by GantMan** [comment]
hey @pedro !

It's `gantman` thanks so much!

**Pull request merged**
