### PR TITLE
Allow to specify env files location as absolute path

### PR DESCRIPTION
**Pull request by baspellis**
Allow to specify an absolute path for the configuration files for different environments. If envFile is not found try to load it as absolute path.

### CODE REVIEW

**Comment by nonameolsson** [comment]
What is the status on this PR? Is there something that prevents it from being merged?

@baspellis Will this allow us to put the .env-file in a custom location, and not only in project root?

**Comment by baspellis** [comment]
@nonameolsson yes, that is exactly the reason for this pull request

**Comment by nonameolsson** [comment]
@baspellis Great! Will it automatically find the file, or is it required to specify the path?

**Comment by baspellis** [comment]
With this PR you can specify the path a an absolute path (eg "/home/user/.env.staging")

**Comment by nonameolsson** [comment]
@baspellis Sounds good. But is it possible to specify a path relative to the project root?

**Comment by baspellis** [comment]
@nonameolsson For a path relative to the project root you don't need this PR

**Comment by Naoto-Ida** [comment]
Hi @baspellis, could we get this merged in? It would be a great addition!

**Comment by baspellis** [comment]
@Naoto-Ida I don't have write access. @pedro is your man.

**Comment by pedro** [comment]
Oops, sorry for dropping the ball folks! Merged manually to fix a conflict, released in 0.8.1

**Pull request closed without merging**
