### PR TITLE
dotenv.gradle: Set environment variables per variant buildConfig task, with .env fallback

### PR DESCRIPTION
**Pull request by hdchan**
This pull request is meant to address https://github.com/luggit/react-native-config/issues/135

In the case of utilizing this library with BuddyBuild, an **app:assemble** command will only set the environment variables once during the gradle build. This update will hook the task of setting the environment variable before a **generate buildConfig** task. This allows us to hook into each variant that is created in the project.

### CODE REVIEW

**Comment by chase-seibert** [comment]
+1

**Comment by batical** [comment]
Hello , following my message here  #178. I took time to test the android part and it's fixed my issue.

I even tested on the new appcenter.ms to build and it worked :) thanks @hdchan

**Comment by pedro** [comment]
Amazing, thank you @hdchan! <3

**Comment by janvogt** [comment]
Good idea, the bad thing with this PR is, that it breaks configurations without a general .env file. This was kind of hard to debug. I suggest either document the common .env file to be required or to ignore the ERRNOENT when reading the non-existent .env file when a environment specific file ist set in /tmp/envfile. 

Unfortunately I don't feel confident enough in Ruby to make the changes myself in ios/ReactNativeConfig/BuildDotenvConfig.ruby, thus I stick with adding an empty .env file for now.

**Comment by pedro** [comment]
Yeah! In the latest version it should just print an error/move on if `.env` is not present :+1:

**Pull request merged**
