### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by tonmanayo**
update android gradle files please, you are using deprecated settings

### CODE REVIEW

**Comment by kaladivo** [comment]
This throws an error when building. 

In order to fix it `google()` needs to be added into `buildscript.repositories`. So it looks something like: 

```
buildscript {
    repositories {
        jcenter()
        google()
    }
...
```

**Comment by kaladivo** [comment]
Also, `Google Play will soon require that apps target API level 26 or higher`. Can we update `targetSdkVersion` and `compileSdkVersion` to 26?

**Comment by luissmg** [comment]
Why don't put it dynamic? Use the project config if defined? Like `react-native` does I guess

**Comment by javaknight1** [comment]
What is the status on this issue? When will this be merged into master and tagged for prod?

**Comment by tonmanayo** [comment]
@kaladivo can you check this for me please

**Pull request closed without merging**
