### PR TITLE
Include ts definitions in package.json

### PR DESCRIPTION
**Pull request by toytonic**
I saw that you have a small file with ts definitions. Would be great to have it included in package.json.

### CODE REVIEW

**Comment by henrikra** [comment]
Sorry I am noob at TS. So my question is that now when I import normally react-native-config methods I get intellisense automatically?

**Comment by r3nya** [comment]
@henrikra yeah! We need to merge it and everything will ok!

**Comment by toytonic** [comment]
If you import a module in TS that is written in JS without a definition file, tsc will only give you an implicit any type when referencing it. Depending on your ts-config that could also give you an compilation error (no-implicit-any: true). Having the definition file referenced in your package.json, tsc will automatically find it and provide you with given types.

**Comment by toytonic** [comment]
So... Do you wanna merge it in? :)

**Comment by pedro** [comment]
Oops! Sorry for the delay folks, getting this in and releasing.

**Pull request merged**
