### PR TITLE
Fix backward compatibility for RN < 0.47

### PR DESCRIPTION
**Pull request by Amurmurmur**

### CODE REVIEW

**Comment by Onumis** [comment]
LGTM, can we get this merged and released?

**Comment by MarkMGray** [comment]
Is there an ETA on this? We verified in our case that this fixes the compatibility issue.

**Comment by Onumis** [comment]
Just upgraded to react-native 0.48 and applied these changes, and all is working fine

**Comment by pedro** [comment]
Ugh, so sorry for the delay folks! Releasing now.

**Comment by pedro** [comment]
It's in 0.6.1

**Pull request merged**
