### PR TITLE
Updated podspec in order to use it in a react-native project as a coc…

### PR DESCRIPTION
**Pull request by skulawik**
…oapod reference with a running BuildDotenvConfig and their necessary build variables

### CODE REVIEW

**Comment by skulawik** [comment]
Added some documentation and fixes for the ruby script

**Comment by ptgamr** [comment]
Will this one fix the issue the ruby script is not executed & 'GeneratedDotEnv' is not found ?

**Comment by skulawik** [comment]
Yes with the second commit. Build script will only be executed by running pod install when using cocapods.

**Comment by itchingpixels** [comment]
hi! what's the status of this? bumping into the same issue...

**Comment by DLevai94** [comment]
What's the status of this PR? @skulawik will you update to make it work and @pedro will be able to merge?

I tried this by copy-paste and didn't work for me.

Thanks

**Comment by povloid** [comment]
Hi all! I am sorry. As variant:


```pod 'react-native-config', path: '../node_modules/react-native-config'```

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-config' then
      phase = target.new_shell_script_build_phase("Build env file")
      phase.shell_script = "cd ../../node_modules/react-native-config/"\
                           " && export SYMROOT=./ios/ReactNativeConfig"\
                           " && export BUILD_DIR=./ios/ReactNativeConfig"\
                           " && ruby ./ios/ReactNativeConfig/BuildDotenvConfig.ruby"
      target.build_phases.move(phase,0)
    end
  end
end
```

**Comment by DLevai94** [comment]
@povloid and this works with your BuildDotenvConfig.ruby or the latest one from the main branch?

Because in my project it isn't working and I can't find a solution. :(

**Comment by povloid** [comment]
I use re-natal 8.0 and RN 0.5.2. also react-native-config 0.10.0

**Comment by DLevai94** [comment]
@povloid me too, but it isn't working with any of my projects. What steps are you doing to make this work? Could you please help?

**Comment by povloid** [comment]
@DLevai94 , I updated my description in my first post

**Comment by povloid** [comment]
@DLevai94 I am sorry. My first variant was work cuz I did have `.env` in parent folder of my project. If you'r `.env` placed in root of project then do change script to:
```
      phase.shell_script = "cd ../../node_modules/react-native-config/ios"\
                           " && export SYMROOT=./ReactNativeConfig"\
                           " && export BUILD_DIR=./ReactNativeConfig"\
                           " && ruby ./ReactNativeConfig/BuildDotenvConfig.ruby"
```

**Comment by DLevai94** [comment]
@selfeky It works nicely if you downgrade React Native to v0.49.5

**Comment by pedro** [comment]
Won't this require a `pod install` whenever we update the env?

It seems like in [cocoapods 1.4.0 we'll be able to properly set build phases from the podspec](https://github.com/CocoaPods/CocoaPods/pull/7092), but I couldn't make it work yet (1.4.0 is in beta so might not be 100% yet).

I'm closing for now, feel free to reopen if you can make it work with the latest example app in this repo (now updated to RN 0.50).

Thank you!

**Pull request closed without merging**
